FROM node:12
MAINTAINER Chris Tooley <ctooley@foundryspatial.com>

ENV NODE_ENV="production"
EXPOSE 8080
VOLUME /data
WORKDIR /data
ENTRYPOINT ["node", "/usr/src/app/", "-p", "8080"]

RUN mkdir -p /usr/src/app
COPY / /usr/src/app
RUN cd /usr/src/app && npm install --production
