version: '2.2'
services:
  tileserver-gl:
    container_name: tileserver-gl
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - 8085:80
